Issue 17
OFMFWG/OFMF-Reference pull request #22
Opened 2023-09-06 14:11 UTC by bmesnet

Modified `setup.sh ` file to:
- Remove the Redfish-Interface-Emulator cloning
- Remove the creation of a specific working directory
- Move the default virtual environment creation to an option
- Added python3 release checking
Added the few missing files copying them from Redfish-Interface-Emulator github:
- api_emulator/version.py
- api_emulator/account_service.py
- api_emulator/resource_dictionary.py
- api_emulator/exceptions.py
- templates/*
- Updated README.md

2023-09-15 12:56 UTC, christian-pinto requested changes
It is mostly about adding the proper license headers to some of the files. Otherwise it all looks good to me.

2023-09-15 12:56 UTC, christian-pinto commented on templates/browse.html
If this file was taken from the DMTF Redfish emulator we should add their header. Just to make sure we give credit on whatever we re-use.

2023-09-15 12:56 UTC, christian-pinto commented on templates/index.html
Same as for the previous comment on "browse.html".

2023-09-15 14:06 UTC, bmesnet commented on templates/browse.html
header added

2023-09-15 14:06 UTC, bmesnet commented on templates/index.html
header added

2023-09-18 08:00 UTC, christian-pinto approved these changes
Thanks @bmesnet looks good now

2023-09-18 08:37 UTC, merged

2023-09-18 08:39 UTC, christian-pinto commented
This closes issue #17

2023-09-18 08:43 UTC, christian-pinto commented
Closes #17